public class MailForTests {
    /*public static void createMail(Id UserId){
        System.debug('Going in');
                      Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
              String[] toAddresses = new String[] {'RR.PACE.UI@gmail.com'};
              mail.setToAddresses(toAddresses);
              mail.setSenderDisplayName('Salesforce Support');
              mail.setSubject('New portal user created : ' + UserId);
              mail.setPlainTextBody('Your portal user account: ' + UserId +' has been created.');
              Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }*/
}